TARGET = test_config

SOURCE = /home/hxk/C++Project/webserver/code/config/config.cpp test_config.cpp

INCL = -I/home/hxk/C++Project/webserver/code/config/  -I/home/hxk/C++Project/webserver/code/common/

$(TARGET) : $(SOURCE)
	$(CXX) $^ -o $@ $(INCL) -lyaml-cpp