test:
	g++ /home/hxk/project/webserver/test/future/future/test_FutureWhenAllIter.cpp	\
	-o test_FutureWhenAllIter	\
	-I /home/hxk/project/webserver/	\
	&&	\
	g++ /home/hxk/project/webserver/test/future/future/test_FutureWhenAll.cpp	\
	-o test_FutureWhenAll	\
	-I /home/hxk/project/webserver/	\