TARGET = test_log

SOURCE = /home/hxk/project/webserver/test/log/test_log.cpp /home/hxk/project/webserver/code/util/util.cpp /home/hxk/project/webserver/code/util/timeUtil.cpp

INCL = -I/home/hxk/project/webserver/code/log/ -I/home/hxk/project/webserver/

$(TARGET) : $(SOURCE)
	$(CXX) $^ -o $@ $(INCL) -lyaml-cpp