TARGET = test_log

SOURCE = /home/hxk/C++Project/webserver/test/log/test_log.cpp /home/hxk/C++Project/webserver/code/config/config.cpp /home/hxk/C++Project/webserver/code/common/util.cpp

INCL = -I/home/hxk/C++Project/webserver/code/log/ -I/home/hxk/C++Project/webserver/code/config -I/home/hxk/C++Project/webserver/code/common

$(TARGET) : $(SOURCE)
	$(CXX) $^ -o $@ $(INCL) -lyaml-cpp