
test:
	g++ /home/hxk/project/webserver/test/timeutil/test_timeutil.cpp	\
	/home/hxk/project/webserver/code/util/TimeUtil.cpp -o test_timeutil \
	-I /home/hxk/project/webserver/		\
	&&	\
	g++ /home/hxk/project/webserver/test/timeutil/test_timer.cpp	\
	/home/hxk/project/webserver/code/util/Timer.cpp -o test_timer \
	-I /home/hxk/project/webserver/		

clean:
	rm test_timeutil && rm test_timer