TARGET = test_timeutil

SOURCE = /home/hxk/C++Project/webserver/test/timeutil/test_timeutil.cpp /home/hxk/C++Project/webserver/code/common/timeUtil.cpp

INCL = -I/home/hxk/C++Project/webserver/code/common

$(TARGET) : $(SOURCE)
	$(CXX) $^ -o $@ $(INCL)